volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: postgres -p 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: wraz/foodgram-backend:latest
    env_file: .env
    volumes:
      - static:/app/static
      - ./media:/app/media
      - ./data:/app/data
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py load_ingredients &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8001"

  frontend:
    image: wraz/foodgram-frontend:latest
    env_file: .env
    command: >
      sh -c "cp -r /app/build/. /app/static/frontend/ &&
            cp -r /app/static/. /static/"
    volumes:
      - ./static:/app/static
      - ./static:/static

  nginx:
    image: nginx:1.21
    ports:
      - "8001:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - backend